name: Checked C Clang CI [WINDOWS]

on:
  workflow_dispatch:
    inputs:
      clang_branch:
        description: 'Clang Branch name'
        required: true
        default: 'main'
      checkedc_branch:
        description: 'Checked-C Branch name'
        required: true
        default: 'main'
      checkedc_repo:
        description: 'Checked-C Repo name'
        required: true
        default: 'https://github.com/checkedc/checkedc.git'
      clang_repo:
        description: 'Clang Repo name'
        required: true
        default: 'https://github.com/checkedc/checkedc-llvm-project.git'
      testType:
        description: 'Test Type'
        required: true
        default: 'CheckedC_clang'
        options: ['CheckedC_clang', 'CheckedC_LLVM', 'CheckedC_tests', 'CheckedC']
      Architecture:
        description: 'Architecture'
        required: true
        default: 'AMD64'
        options: ['X86', 'AMD64']
      build_checkedc_clean:
        description: 'Clean directories before building'
        required: true
        default: 'No'
        options: ['No','Yes']

env:
  builddir: "${{github.workspace}}\\b\\build"
  BUILDCONFIGURATION: "Release"
  BUILD_BINARIESDIRECTORY: "${{github.workspace}}\\b"
  BUILD_SOURCESDIRECTORY: "${{github.workspace}}"
  TEST_TARGET_ARCH:  ${{ github.event.inputs.Architecture}}
  RUN_LOCAL:  "no"
  TEST_SUITE: ${{ github.event.inputs.testType}}

jobs:
  test_CheckedC_Clang_on_windows :
    name: Build Checked C clang and test it on Windows
    runs-on: [ Windows, X64 ]
    steps:
      - name: Checkout Checked C Clang code
        uses: actions/checkout@v2
        with:
          path: ${{env.BUILD_SOURCESDIRECTORY}}
      - name: Run build-and-test.bat script
        env:
          TEST_SUITE: ${{ github.event.inputs.testType}}
          TEST_TARGET_ARCH: ${{ github.event.inputs.Architecture}}
          CLANG_BRANCH: ${{ github.event.inputs.clang_branch}}
          CHECKEDC_BRANCH: ${{ github.event.inputs.checkedc_branch}}
          CLANG_REPO: ${{ github.event.inputs.clang_repo}}
          CHECKEDC_REPO: ${{ github.event.inputs.checkedc_repo}}
          BUILD_CHECKEDC_CLEAN: ${{ github.event.inputs.build_checkedc_clean}}
        shell: cmd
        run: |
         cd ${{env.BUILD_SOURCESDIRECTORY}}\test_scripts\automation\Windows\
         build-and-test.bat
